services:
  mysql:
    image: mysql:8
    container_name: longphungsql
    restart: always
    environment:
      MYSQL_DATABASE: longphungapp
      MYSQL_ROOT_PASSWORD: Kien@123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - longphung-network

  backend:
    build: ./LongPhungBE
    container_name: longphungbe
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: longphungsql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Kien@123
      CORS_ALLOWED_ORIGINS: https://192.168.1.4
      COOKIE_SECURE: true
      COOKIE_SAMESITE: none
    ports:
      - "8080:8080"
    networks:
      - longphung-network

  frontend:
    build:
      context: ./LongPhungFE
      args:
        - REACT_APP_BASE_URL=https://192.168.1.4
    container_name: longphungfe
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./LongPhungFE/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./LongPhungFE/certs/privkey.pem:/etc/nginx/certs/privkey.pem:ro
      # - ./certbot/www:/usr/share/nginx/html
      
    networks:
      - longphung-network

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #     - ./certbot/copy-certs.sh:/copy-certs.sh:ro
  #     - ./LongPhungFE/certs:/app-certs
  #   entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/certbot --quiet && /copy-certs.sh; done"
  #   networks:
  #     - longphung-network

volumes:
  mysql_data:

networks:
  longphung-network:
    driver: bridge
