# Sử dụng Node để build React trước
# FROM node:20 AS build-stage
# WORKDIR /app
# COPY . .
# RUN npm install

# ARG REACT_APP_BASE_URL
# ENV REACT_APP_BASE_URL=${REACT_APP_BASE_URL}

# RUN chmod +x node_modules/.bin/react-scripts

# RUN npm run build && ls -la /app/build

# Sử dụng Nginx để serve React app
FROM nginx:1.27.4
# COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/certs /etc/nginx/certs
COPY build /usr/share/nginx/html

EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
